// import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// import Header from "./components/Header/Header";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="min-h-full flex flex-col">
//         <Header />
//         <main> {children}</main>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Header from "./components/Header/Header";

export const metadata: Metadata = {
  title: "My App",
  description: "My project",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
